export const brandAssets = {
  wordmarkDark: require("../../../assets/wordmark/wordmark-h-dark-preview.png"),
  wordmarkLight: require("../../../assets/wordmark/wordmark-h-light-v2-preview.png"),
  iconPrimary: require("../../../assets/icon/icon-primary-512.png"),
};

export const outfitImageAssets: Record<string, number> = {
  "assets/outfits/weatheron-outfit-ankle-rain-boots-v1.png": require("../../../assets/outfits/weatheron-outfit-ankle-rain-boots-v1.png"),
  "assets/outfits/weatheron-outfit-black-turtleneck-v1.png": require("../../../assets/outfits/weatheron-outfit-black-turtleneck-v1.png"),
  "assets/outfits/weatheron-outfit-cardigan-v1.png": require("../../../assets/outfits/weatheron-outfit-cardigan-v1.png"),
  "assets/outfits/weatheron-outfit-chelsea-boots-v1.png": require("../../../assets/outfits/weatheron-outfit-chelsea-boots-v1.png"),
  "assets/outfits/weatheron-outfit-chino-shorts-v1.png": require("../../../assets/outfits/weatheron-outfit-chino-shorts-v1.png"),
  "assets/outfits/weatheron-outfit-compact-umbrella-v1.png": require("../../../assets/outfits/weatheron-outfit-compact-umbrella-v1.png"),
  "assets/outfits/weatheron-outfit-crossbody-bag-v1.png": require("../../../assets/outfits/weatheron-outfit-crossbody-bag-v1.png"),
  "assets/outfits/weatheron-outfit-knit-sweater-v1.png": require("../../../assets/outfits/weatheron-outfit-knit-sweater-v1.png"),
  "assets/outfits/weatheron-outfit-light-rain-jacket-v1.png": require("../../../assets/outfits/weatheron-outfit-light-rain-jacket-v1.png"),
  "assets/outfits/weatheron-outfit-linen-tshirt-v1.png": require("../../../assets/outfits/weatheron-outfit-linen-tshirt-v1.png"),
  "assets/outfits/weatheron-outfit-low-sneakers-v1.png": require("../../../assets/outfits/weatheron-outfit-low-sneakers-v1.png"),
  "assets/outfits/weatheron-outfit-navy-cap-v1.png": require("../../../assets/outfits/weatheron-outfit-navy-cap-v1.png"),
  "assets/outfits/weatheron-outfit-oxford-shirt-v1.png": require("../../../assets/outfits/weatheron-outfit-oxford-shirt-v1.png"),
  "assets/outfits/weatheron-outfit-pleated-skirt-v1.png": require("../../../assets/outfits/weatheron-outfit-pleated-skirt-v1.png"),
  "assets/outfits/weatheron-outfit-ribbed-beanie-v1.png": require("../../../assets/outfits/weatheron-outfit-ribbed-beanie-v1.png"),
  "assets/outfits/weatheron-outfit-slim-slacks-v1.png": require("../../../assets/outfits/weatheron-outfit-slim-slacks-v1.png"),
  "assets/outfits/weatheron-outfit-striped-long-sleeve-v1.png": require("../../../assets/outfits/weatheron-outfit-striped-long-sleeve-v1.png"),
  "assets/outfits/weatheron-outfit-tan-loafers-v1.png": require("../../../assets/outfits/weatheron-outfit-tan-loafers-v1.png"),
  "assets/outfits/weatheron-outfit-tapered-joggers-v1.png": require("../../../assets/outfits/weatheron-outfit-tapered-joggers-v1.png"),
  "assets/outfits/weatheron-outfit-trench-coat-v1.png": require("../../../assets/outfits/weatheron-outfit-trench-coat-v1.png"),
  "assets/outfits/weatheron-outfit-waterproof-sneakers-v1.png": require("../../../assets/outfits/weatheron-outfit-waterproof-sneakers-v1.png"),
  "assets/outfits/weatheron-outfit-wide-denim-v1.png": require("../../../assets/outfits/weatheron-outfit-wide-denim-v1.png"),
  "assets/outfits/weatheron-outfit-windbreaker-v1.png": require("../../../assets/outfits/weatheron-outfit-windbreaker-v1.png"),
  "assets/outfits/weatheron-outfit-zip-hoodie-v1.png": require("../../../assets/outfits/weatheron-outfit-zip-hoodie-v1.png"),
};

export const placeImageAssets = {
  baseball: require("../../../assets/place-categories/weatheron-place-baseball-v1.png"),
  beach: require("../../../assets/place-categories/weatheron-place-beach-v1.png"),
  mountain: require("../../../assets/place-categories/weatheron-place-mountain-v1.png"),
  airport: require("../../../assets/place-categories/weatheron-place-airport-v1.png"),
  hotel: require("../../../assets/place-categories/weatheron-place-hotel-v1.png"),
};

export const destinationImageAssets: Record<string, number> = {
  "kr-gangneung-anmok-beach": require("../../../assets/destinations/weatheron-destination-anmok-beach-gen-v1.jpg"),
  "kr-jamsil-baseball-stadium": require("../../../assets/destinations/weatheron-destination-jamsil-stadium-gen-v1.jpg"),
  "jp-tokyo-station": require("../../../assets/destinations/weatheron-destination-tokyo-station-gen-v1.jpg"),
  "jp-shinsaibashi-station": require("../../../assets/destinations/weatheron-destination-shinsaibashi-gen-v1.jpg"),
  "jp-namba-station": require("../../../assets/destinations/weatheron-destination-namba-gen-v1.jpg"),
  "global-new-york-central-park": require("../../../assets/destinations/weatheron-destination-central-park-gen-v1.jpg"),
};

export const destinationFallbackImageAsset = require("../../../assets/destinations/weatheron-destination-generic-city-gen-v1.jpg");

export const destinationVisualAssets: Record<string, number> = {
  "KR:church": require("../../../assets/destinations/weatheron-destination-kr-church-gen-v1.jpg"),
  "JP:church": require("../../../assets/destinations/weatheron-destination-jp-church-gen-v1.jpg"),
  "EU:church": require("../../../assets/destinations/weatheron-destination-eu-church-gen-v1.jpg"),
  "KR:temple": require("../../../assets/destinations/weatheron-destination-kr-temple-gen-v1.jpg"),
  "JP:temple": require("../../../assets/destinations/weatheron-destination-jp-shrine-gen-v1.jpg"),
  "KR:football": require("../../../assets/destinations/weatheron-destination-kr-football-stadium-gen-v1.jpg"),
  "JP:football": require("../../../assets/destinations/weatheron-destination-jp-football-stadium-gen-v1.jpg"),
  "EU:football": require("../../../assets/destinations/weatheron-destination-eu-football-stadium-gen-v1.jpg"),
  "KR:school": require("../../../assets/destinations/weatheron-destination-kr-school-gen-v1.jpg"),
  "JP:school": require("../../../assets/destinations/weatheron-destination-jp-school-gen-v1.jpg"),
  "KR:hospital": require("../../../assets/destinations/weatheron-destination-kr-hospital-gen-v1.jpg"),
  "JP:hospital": require("../../../assets/destinations/weatheron-destination-jp-hospital-gen-v1.jpg"),
  "KR:airport": require("../../../assets/destinations/weatheron-destination-kr-airport-gen-v1.jpg"),
  "JP:airport": require("../../../assets/destinations/weatheron-destination-jp-airport-gen-v1.jpg"),
  "KR:mountain": require("../../../assets/destinations/weatheron-destination-kr-mountain-gen-v1.jpg"),
  "JP:mountain": require("../../../assets/destinations/weatheron-destination-jp-mountain-gen-v1.jpg"),
  "KR:museum": require("../../../assets/destinations/weatheron-destination-kr-museum-gen-v1.jpg"),
  "JP:museum": require("../../../assets/destinations/weatheron-destination-jp-museum-gen-v1.jpg"),
  "KR:rail": require("../../../assets/destinations/weatheron-destination-kr-rail-station-gen-v1.jpg"),
  "JP:rail": require("../../../assets/destinations/weatheron-destination-jp-rail-station-gen-v1.jpg"),
  "EU:rail": require("../../../assets/destinations/weatheron-destination-eu-rail-station-gen-v1.jpg"),
  "KR:metro": require("../../../assets/destinations/weatheron-destination-kr-metro-entrance-gen-v1.jpg"),
  "JP:metro": require("../../../assets/destinations/weatheron-destination-jp-metro-entrance-gen-v1.jpg"),
  "EU:metro": require("../../../assets/destinations/weatheron-destination-eu-metro-entrance-gen-v1.jpg"),
  "KR:bus": require("../../../assets/destinations/weatheron-destination-kr-bus-terminal-gen-v1.jpg"),
  "JP:bus": require("../../../assets/destinations/weatheron-destination-jp-bus-terminal-gen-v1.jpg"),
  "KR:ferry": require("../../../assets/destinations/weatheron-destination-kr-ferry-terminal-gen-v1.jpg"),
  "JP:ferry": require("../../../assets/destinations/weatheron-destination-jp-ferry-terminal-gen-v1.jpg"),
  "KR:baseball": require("../../../assets/destinations/weatheron-destination-kr-baseball-stadium-gen-v1.jpg"),
  "JP:baseball": require("../../../assets/destinations/weatheron-destination-jp-baseball-stadium-gen-v1.jpg"),
  "GLOBAL:baseball": require("../../../assets/destinations/weatheron-destination-global-baseball-stadium-gen-v1.jpg"),
  "KR:hotel": require("../../../assets/destinations/weatheron-destination-kr-hotel-gen-v1.jpg"),
  "JP:hotel": require("../../../assets/destinations/weatheron-destination-jp-hotel-gen-v1.jpg"),
  "KR:park": require("../../../assets/destinations/weatheron-destination-kr-park-gen-v1.jpg"),
  "JP:park": require("../../../assets/destinations/weatheron-destination-jp-park-gen-v1.jpg"),
  "KR:amusement": require("../../../assets/destinations/weatheron-destination-kr-amusement-park-gen-v1.jpg"),
  "JP:amusement": require("../../../assets/destinations/weatheron-destination-jp-amusement-park-gen-v1.jpg"),
  "KR:shopping": require("../../../assets/destinations/weatheron-destination-kr-shopping-gen-v1.jpg"),
  "JP:shopping": require("../../../assets/destinations/weatheron-destination-jp-shopping-gen-v1.jpg"),
  "KR:office": require("../../../assets/destinations/weatheron-destination-kr-office-gen-v1.jpg"),
  "JP:office": require("../../../assets/destinations/weatheron-destination-jp-office-gen-v1.jpg"),
  "KR:convention": require("../../../assets/destinations/weatheron-destination-kr-convention-gen-v1.jpg"),
  "JP:convention": require("../../../assets/destinations/weatheron-destination-jp-convention-gen-v1.jpg"),
  "KR:camping": require("../../../assets/destinations/weatheron-destination-kr-camping-gen-v1.jpg"),
  "JP:camping": require("../../../assets/destinations/weatheron-destination-jp-camping-gen-v1.jpg"),
  "KR:ski": require("../../../assets/destinations/weatheron-destination-kr-ski-resort-gen-v1.jpg"),
  "JP:ski": require("../../../assets/destinations/weatheron-destination-jp-ski-resort-gen-v1.jpg"),
  "KR:arena": require("../../../assets/destinations/weatheron-destination-kr-indoor-arena-gen-v1.jpg"),
  "JP:arena": require("../../../assets/destinations/weatheron-destination-jp-indoor-arena-gen-v1.jpg"),
};

export const onboardingAssets = {
  ready: require("../../../assets/onboarding/weatheron-onboarding-o2-ready-5sec-v1.png"),
  destinationCare: require("../../../assets/onboarding/weatheron-onboarding-o6-destination-care-v1.png"),
};

export const uiIconAssets = {
  tabHome: require("../../../assets/ui-icons/tab-home.png"),
  tabOutfit: require("../../../assets/ui-icons/tab-outfit.png"),
  tabDepart: require("../../../assets/ui-icons/tab-depart.png"),
  tabMy: require("../../../assets/ui-icons/tab-my.png"),
  tabSocial: require("../../../assets/ui-icons/tab-social.png"),
  shirt: require("../../../assets/ui-icons/card-shirt.png"),
  umbrella: require("../../../assets/ui-icons/card-umbrella.png"),
  shoe: require("../../../assets/ui-icons/card-shoe.png"),
  depart: require("../../../assets/ui-icons/tab-depart.png"),
  clock: require("../../../assets/ui-icons/card-clock.png"),
  rain: require("../../../assets/ui-icons/card-rain.png"),
  drop: require("../../../assets/ui-icons/card-drop.png"),
  humidity: require("../../../assets/ui-icons/card-humidity.png"),
  wind: require("../../../assets/ui-icons/card-wind.png"),
  uv: require("../../../assets/ui-icons/card-uv.png"),
  check: require("../../../assets/ui-icons/card-check.png"),
  trash: require("../../../assets/ui-icons/card-trash.png"),
  settings: require("../../../assets/ui-icons/card-settings.png"),
  pin: require("../../../assets/ui-icons/card-pin.png"),
  myPermissions: require("../../../assets/ui-icons/my-permissions.png"),
  myAlerts: require("../../../assets/ui-icons/my-alerts.png"),
  myDisplay: require("../../../assets/ui-icons/my-display.png"),
  myPolicy: require("../../../assets/ui-icons/my-policy.png"),
  policyPrivacy: require("../../../assets/ui-icons/policy-privacy.png"),
  policyTerms: require("../../../assets/ui-icons/policy-terms.png"),
  policyLocation: require("../../../assets/ui-icons/policy-location.png"),
  policyOss: require("../../../assets/ui-icons/policy-oss.png"),
};
